[build]
target = "config/x86_64-unknown-none.json"

[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins", "alloc"]

[target.'cfg(target_os = "none")']
rustflags = [
  "-C", "link-arg=-Tpkg/kernel/config/kernel.ld", 
  "-C", "relocation-model=static",  
  "-C", "code-model=kernel"         
]